"""Add booking table

Revision ID: 332d23c7cf1f
Revises: e97d090eee1f
Create Date: 2025-04-27 19:52:34.188849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332d23c7cf1f'
down_revision: Union[str, None] = 'e97d090eee1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.add_column('users', sa.Column('user_bearer_access_token', sa.String(), nullable=True))
    op.drop_column('users', 'user_jwt_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_jwt_access_token', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'user_bearer_access_token')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
